language: php

php:
  - 5.5
  - 7.0

matrix:
  allow_failures:
    - php: 7.0
    
notifications:
  slack: 
    rooms:
      - esgi-iw:3xesgTA7LDncYCqnA2EShdA5#git
    on_success: always
    on_failure: always
    
  email:
    recipients:
      - driss.belaroussi.sio@gmail.com
      
before_install:
  - composer require friendsofphp/php-cs-fixer

script: ./vendor/bin/php-cs-fixer fix . --dry-run
